define([],
[
	{path:"normalPageDemo/index",name:"一般页面开发", todo:true},
	{path:"naviPageDemo/index",name:"具有导航栏页面开发", todo:true},
	{path:"remDemo/index",name:"rem页面适配", todo:true},
	{path:"pageJumpDemo/index",name:"页面跳转效果", todo:true},
	{path:"pageJumpParamsDemo/index",name:"页面跳转参数传递功能", todo:true},
	{path:"netDemo/index",name:"网络API开发"},
	{path:"netLocalDemo/index",name:"网络本地数据框架"},
	{path:"cacheDemo/index",name:"网络缓存", todo:true},
	{path:"sendCheckDemo/index",name:"网络请求发送策略", todo:true},
	{path:"listViewDemo/index",name:"列表开发", todo:true},
	{path:"dialogDemo/index",name:"对话框开发", todo:true},
	{path:"refreshViewDemo/index",name:"下拉刷新开发"},
	{path:"refreshListViewDemo/index",name:"列表刷新开发"},	
]);