define([],
[
	{path:"normalPageDemo/index",name:"一般页面开发"},
	{path:"naviPageDemo/index",name:"具有导航栏页面开发"},
	{path:"remDemo/index",name:"rem页面适配"},
	{path:"pageJumpDemo/index",name:"页面跳转效果"},
	{path:"pageJumpParamsDemo/index",name:"页面跳转参数传递功能", todo:true},
	{path:"netDemo/index",name:"网络API开发"},
	{path:"netLocalDemo/index",name:"网络本地数据框架"},
	{path:"cacheDemo/index",name:"网络缓存", todo:true},
	{path:"sendCheckDemo/index",name:"网络请求发送策略", todo:true},
	{path:"alertDemo/index",name:"Alert"},
	{path:"refreshViewDemo/index",name:"下拉刷新"},
	{path:"refreshListViewDemo/index",name:"列表刷新"},	
]);